[2023-02-20 12:55:39,915] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: autoetl-coordinates.get_input_data manual__2023-02-20T12:55:37.672912+00:00 [queued]>
[2023-02-20 12:55:39,929] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: autoetl-coordinates.get_input_data manual__2023-02-20T12:55:37.672912+00:00 [queued]>
[2023-02-20 12:55:39,930] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-20 12:55:39,932] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-20 12:55:39,933] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-20 12:55:39,948] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_input_data> on 2023-02-20 12:55:37.672912+00:00
[2023-02-20 12:55:39,955] {standard_task_runner.py:52} INFO - Started process 316 to run task
[2023-02-20 12:55:39,960] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'autoetl-coordinates', 'get_input_data', 'manual__2023-02-20T12:55:37.672912+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/autoetl-coordinates.py', '--cfg-path', '/tmp/tmpk_y7vtr9', '--error-file', '/tmp/tmpivbr6el1']
[2023-02-20 12:55:39,963] {standard_task_runner.py:80} INFO - Job 6: Subtask get_input_data
[2023-02-20 12:55:40,028] {task_command.py:369} INFO - Running <TaskInstance: autoetl-coordinates.get_input_data manual__2023-02-20T12:55:37.672912+00:00 [running]> on host 08ba3386fdbc
[2023-02-20 12:55:40,114] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=autoetl-coordinates
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T12:55:37.672912+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-20T12:55:37.672912+00:00
[2023-02-20 12:55:40,118] {logging_mixin.py:115} INFO - Get Locations URL and Load into Pandas Dataframe
[2023-02-20 12:55:43,999] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:189 DtypeWarning: Columns (11,12,14,20) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-02-20 12:55:53,201] {logging_mixin.py:115} INFO - Get buildings data
[2023-02-20 12:56:07,333] {logging_mixin.py:115} INFO - Get parcels data
[2023-02-20 12:56:07,859] {logging_mixin.py:115} WARNING - Downloading...
[2023-02-20 12:56:07,861] {logging_mixin.py:115} WARNING - From: https://drive.google.com/uc?id=137bCzf0qEPLwKTgNxeAAjTs5MvyTlxWA
[2023-02-20 12:56:07,862] {logging_mixin.py:115} WARNING - To: /opt/***/data/inputs/ms_hinds_parcels.ndgeojson.gz
[2023-02-20 12:56:07,874] {logging_mixin.py:115} WARNING -   0%|          | 0.00/42.1M [00:00<?, ?B/s]
[2023-02-20 12:56:07,995] {logging_mixin.py:115} WARNING -   9%|8         | 3.67M/42.1M [00:00<00:01, 30.6MB/s]
[2023-02-20 12:56:08,101] {logging_mixin.py:115} WARNING -  16%|#6        | 6.82M/42.1M [00:00<00:01, 30.0MB/s]
[2023-02-20 12:56:08,201] {logging_mixin.py:115} WARNING -  26%|##6       | 11.0M/42.1M [00:00<00:00, 35.1MB/s]
[2023-02-20 12:56:08,305] {logging_mixin.py:115} WARNING -  39%|###8      | 16.3M/42.1M [00:00<00:00, 41.2MB/s]
[2023-02-20 12:56:08,410] {logging_mixin.py:115} WARNING -  52%|#####2    | 22.0M/42.1M [00:00<00:00, 46.0MB/s]
[2023-02-20 12:56:08,540] {logging_mixin.py:115} WARNING -  64%|######3   | 26.7M/42.1M [00:00<00:00, 42.2MB/s]
[2023-02-20 12:56:08,649] {logging_mixin.py:115} WARNING -  75%|#######4  | 31.5M/42.1M [00:00<00:00, 42.6MB/s]
[2023-02-20 12:56:08,750] {logging_mixin.py:115} WARNING -  90%|########9 | 37.7M/42.1M [00:00<00:00, 48.5MB/s]
[2023-02-20 12:56:08,813] {logging_mixin.py:115} WARNING - 100%|##########| 42.1M/42.1M [00:00<00:00, 44.8MB/s]
[2023-02-20 12:56:08,832] {logging_mixin.py:115} INFO - Extract and save gzip file
[2023-02-20 12:56:20,044] {python.py:173} INFO - Done. Returned value was: None
[2023-02-20 12:56:20,072] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=autoetl-coordinates, task_id=get_input_data, execution_date=20230220T125537, start_date=20230220T125539, end_date=20230220T125620
[2023-02-20 12:56:20,137] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-20 12:56:20,184] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
