[2023-02-19 14:49:00,466] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: autoetl-coordinates.get_input_data manual__2023-02-19T14:48:57.378576+00:00 [queued]>
[2023-02-19 14:49:00,479] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: autoetl-coordinates.get_input_data manual__2023-02-19T14:48:57.378576+00:00 [queued]>
[2023-02-19 14:49:00,481] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-19 14:49:00,482] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-19 14:49:00,483] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-19 14:49:00,498] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_input_data> on 2023-02-19 14:48:57.378576+00:00
[2023-02-19 14:49:00,505] {standard_task_runner.py:52} INFO - Started process 629 to run task
[2023-02-19 14:49:00,510] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'autoetl-coordinates', 'get_input_data', 'manual__2023-02-19T14:48:57.378576+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/autoetl-coordinates.py', '--cfg-path', '/tmp/tmp37owezyt', '--error-file', '/tmp/tmpbt8ira7w']
[2023-02-19 14:49:00,513] {standard_task_runner.py:80} INFO - Job 6: Subtask get_input_data
[2023-02-19 14:49:00,590] {task_command.py:369} INFO - Running <TaskInstance: autoetl-coordinates.get_input_data manual__2023-02-19T14:48:57.378576+00:00 [running]> on host 28bff766bd86
[2023-02-19 14:49:00,677] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=autoetl-coordinates
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-19T14:48:57.378576+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-19T14:48:57.378576+00:00
[2023-02-19 14:49:00,680] {logging_mixin.py:115} INFO - Get Locations URL and Load into Pandas Dataframe
[2023-02-19 14:49:03,791] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:189 DtypeWarning: Columns (11,12,14,20) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-02-19 14:49:12,471] {logging_mixin.py:115} INFO - Get buildings data
[2023-02-19 14:49:26,676] {logging_mixin.py:115} INFO - Get parcels data
[2023-02-19 14:49:27,456] {logging_mixin.py:115} WARNING - Downloading...
[2023-02-19 14:49:27,457] {logging_mixin.py:115} WARNING - From: https://drive.google.com/uc?id=137bCzf0qEPLwKTgNxeAAjTs5MvyTlxWA
[2023-02-19 14:49:27,458] {logging_mixin.py:115} WARNING - To: /opt/***/data/ms_hinds_parcels.ndgeojson.gz
[2023-02-19 14:49:27,467] {logging_mixin.py:115} WARNING -   0%|          | 0.00/42.1M [00:00<?, ?B/s]
[2023-02-19 14:49:27,581] {logging_mixin.py:115} WARNING -   6%|6         | 2.62M/42.1M [00:00<00:01, 23.4MB/s]
[2023-02-19 14:49:27,685] {logging_mixin.py:115} WARNING -  12%|#2        | 5.24M/42.1M [00:00<00:01, 24.4MB/s]
[2023-02-19 14:49:27,794] {logging_mixin.py:115} WARNING -  19%|#8        | 7.86M/42.1M [00:00<00:01, 24.2MB/s]
[2023-02-19 14:49:27,900] {logging_mixin.py:115} WARNING -  29%|##8       | 12.1M/42.1M [00:00<00:00, 30.2MB/s]
[2023-02-19 14:49:28,001] {logging_mixin.py:115} WARNING -  40%|###9      | 16.8M/42.1M [00:00<00:00, 35.9MB/s]
[2023-02-19 14:49:28,111] {logging_mixin.py:115} WARNING -  50%|####9     | 21.0M/42.1M [00:00<00:00, 36.7MB/s]
[2023-02-19 14:49:28,219] {logging_mixin.py:115} WARNING -  60%|#####9    | 25.2M/42.1M [00:00<00:00, 37.4MB/s]
[2023-02-19 14:49:28,324] {logging_mixin.py:115} WARNING -  70%|######9   | 29.4M/42.1M [00:00<00:00, 38.2MB/s]
[2023-02-19 14:49:28,426] {logging_mixin.py:115} WARNING -  81%|########1 | 34.1M/42.1M [00:00<00:00, 40.5MB/s]
[2023-02-19 14:49:28,533] {logging_mixin.py:115} WARNING -  97%|#########7| 40.9M/42.1M [00:01<00:00, 47.9MB/s]
[2023-02-19 14:49:28,553] {logging_mixin.py:115} WARNING - 100%|##########| 42.1M/42.1M [00:01<00:00, 38.8MB/s]
[2023-02-19 14:49:29,745] {logging_mixin.py:115} INFO - Extract and save gzip file
[2023-02-19 14:49:57,603] {python.py:173} INFO - Done. Returned value was: None
[2023-02-19 14:49:57,684] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=autoetl-coordinates, task_id=get_input_data, execution_date=20230219T144857, start_date=20230219T144900, end_date=20230219T144957
[2023-02-19 14:49:58,057] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-02-19 14:49:58,098] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 629. PIDs of all processes in the group: [629]
[2023-02-19 14:49:58,106] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 629
[2023-02-19 14:49:58,110] {process_utils.py:75} INFO - Process psutil.Process(pid=629, status='terminated', exitcode=0, started='14:48:59') (629) terminated with exit code 0
